### ISSUE TITLE
Add Number of Repository Stars next to package

### ISSUE THREAD

**Issue by Kyriakos-Michael** [vuejs/awesome-vue#4036] opened 2023-04-20 12:41 UTC
Add the Number of Repository Stars next to the package to easily compare usage and maintainability.

**Comment by Jogai** [comment] 2023-04-22 09:40
Only issue is that Stars don't necessarily indicate usage and maintainability. Maybe last commit, and a graph of downloads each month?

**Comment by posva** [comment] 2023-05-01 07:07
Duplicate of https://github.com/vuejs/awesome-vue/issues/2564

**Closed by posva** 2023-05-01 07:07 UTC
