### ISSUE TITLE
remove VueJS I*sra*el - Facebook Page

### ISSUE THREAD

**Issue by moHaHa** [vuejs/awesome-vue#4115] opened 2023-11-13 11:14 UTC

**Comment by moHaHa** [comment] 2023-11-13 11:15
now Isreal planning to take Gaza from us also
Still this country listed as a normal country?! ... It is always and still is a country based on the occupation of Palestine then changed that the land was taken to Israel, and anyone who takes its name that means he supports the occupation that happened from 1948 to now, and the Gaza Genocide that is in progress

https://twitter.com/MostGaza
https://twitter.com/hashtag/GazaGenocide

**Comment by moHaHa** [comment] 2023-11-13 11:16
#2766

**Comment by Jogai** [comment] 2023-11-13 16:36
Duplicate of #4017

**Closed by Jogai** 2023-11-13 16:36 UTC

**Comment by moHaHa** [comment] 2023-11-14 17:40
@Jogai  

You are stubborn.. It is not a big deal to remove them.. but you will pay the price for that
Whether you like it or not, you are from the nation of Muhammad, and you will be asked about your testimony to the oneness of the Creator (GOD) and the message of Muhammad (first of all) , and your positions second.

go and search plz

**Comment by kpandroid** [comment] 2023-11-14 18:06
@moHaHa could you please stop to spam topics with your stupid ideas. Thanks.
